apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapi-deployment
  labels:
    app: authapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
      - name: authpi
        image: tusshark/authapi:3.0
        ports:
        - containerPort: 8080
  

---

apiVersion: v1
kind: Service
metadata:
  name: authapi-service
spec:
  type: NodePort
  selector:
    app: authapi
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010

