
services:

  authapi:
     image: authapi:2.0
     container_name: authapi_container
     ports:
       - "8080:8080"
      
     networks:
       - mysql_network
     depends_on:
       - mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - mysql_network
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: authdb
      MYSQL_USER: tusshar
      MYSQL_PASSWORD: pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  
  
networks:
  mysql_network:
   driver: bridge